//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sql_nhom.Model
{
    using System;
    using System.Collections.Generic;
    using sql_nhom.ViewModel;

    public partial class BAOHANH : BaseViewModel
    {
        private string _MABH;
        public string MABH { get => _MABH; set { _MABH = value; OnPropertyChanged(); } }

        private string _MAXE;
        public string MAXE { get => _MAXE; set { _MAXE = value; OnPropertyChanged(); } }

        private string _MANV;
        public string MANV { get => _MANV; set { _MANV = value; OnPropertyChanged(); } }

        private string _MAKH;
        public string MAKH { get => _MAKH; set { _MAKH = value; OnPropertyChanged(); } }


        private KHACHHANG _KHACHHANG;
        public virtual KHACHHANG KHACHHANG { get => _KHACHHANG; set { _KHACHHANG = value; OnPropertyChanged(); } }


        private NHANVIEN _NHANVIEN;
        public virtual NHANVIEN NHANVIEN { get => _NHANVIEN; set { _NHANVIEN = value; OnPropertyChanged(); } }

        private XE _XE;
        public virtual XE XE { get => _XE; set { _XE = value; OnPropertyChanged(); } }

        
        
        
    }
}
