//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sql_nhom.Model
{
    using System;
    using System.Collections.Generic;
    using sql_nhom.ViewModel;

    public partial class HOADONXUAT : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOADONXUAT()
        {
            this.CHITIETHOADONXUATs = new HashSet<CHITIETHOADONXUAT>();
        }


        private string _MAHDX;
        public string MAHDX { get => _MAHDX; set { _MAHDX = value; OnPropertyChanged(); } }

        private string _MANV;
        public string MANV { get => _MANV; set { _MANV = value; OnPropertyChanged(); } }

        private string _MAKH;
        public string MAKH { get => _MAKH; set { _MAKH = value; OnPropertyChanged(); } }

        private System.DateTime _NGAYXUAT;
        public System.DateTime NGAYXUAT { get => _NGAYXUAT; set { _NGAYXUAT = value; OnPropertyChanged(); } }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETHOADONXUAT> CHITIETHOADONXUATs { get; set; }
    

        private KHACHHANG _KHACHHANG;
        public virtual KHACHHANG KHACHHANG { get => _KHACHHANG; set { _KHACHHANG = value; OnPropertyChanged(); } }

        private NHANVIEN _NHANVIEN;
        public virtual NHANVIEN NHANVIEN { get => _NHANVIEN; set { _NHANVIEN = value; OnPropertyChanged(); } }
    }
}
