//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sql_nhom.Model
{
    using System;
    using System.Collections.Generic;
    using sql_nhom.ViewModel;

    public partial class XE : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public XE()
        {
            this.BAOHANHs = new HashSet<BAOHANH>();
            this.CHITIETHOADONNHAPs = new HashSet<CHITIETHOADONNHAP>();
            this.CHITIETHOADONXUATs = new HashSet<CHITIETHOADONXUAT>();
        }
    
        private string _MAXE;
        public string MAXE { get => _MAXE; set { _MAXE = value; OnPropertyChanged(); } }

        private string _TENXE;
        public string TENXE { get => _TENXE; set { _TENXE = value; OnPropertyChanged(); } }

        private string _MALOAI;
        public string MALOAI { get => _MALOAI; set { _MALOAI = value; OnPropertyChanged(); } }

        private string _MANCC;
        public string MANCC { get => _MANCC; set { _MANCC = value; OnPropertyChanged(); } }

        private int _SOLUONG;
        public int SOLUONG { get => _SOLUONG; set { _SOLUONG = value; OnPropertyChanged(); } }

        private double _GIA;
        public double GIA { get => _GIA; set { _GIA = value; OnPropertyChanged(); } }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAOHANH> BAOHANHs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETHOADONNHAP> CHITIETHOADONNHAPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETHOADONXUAT> CHITIETHOADONXUATs { get; set; }
       

        private LOAIXE _LOAIXE;
        public virtual LOAIXE LOAIXE { get => _LOAIXE; set { _LOAIXE = value; OnPropertyChanged(); } }

        private NHACUNGCAP _NHACUNGCAP;
        public virtual NHACUNGCAP NHACUNGCAP { get => _NHACUNGCAP; set { _NHACUNGCAP = value; OnPropertyChanged(); } }
    }
}
